runtime: python310
instance_class: F2
service: pagos-cliente-flask
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker pagos_cliente_flask.app:app
env_variables:
  PROJECT_ID: justicia-digital-gob-mx
vpc_access_connector:
  name: projects/justicia-digital-gob-mx/locations/us-west2/connectors/cupido
